### PR TITLE
Client now consistently shows games ran from client.

### LINKED ISSUE #113: Client sometimes doesn't automatically run match.
Some users are experiencing an issue wherein running a match via the client (Queue > Run Match) does run the match, and saves the matchfile, but does not automatically load said matchfile and display it. Seems to have appeared suddenly. Deleting and reinstalling client does not fix issue.

### PR DESCRIPTION
**Pull request by jbloxham**
Resolves #113 . See https://github.com/battlecode/battlecode-server/pull/377.

### CODE REVIEW

**Comment by vontell** [comment]
Does this get rid of the console errors? I think that is an easy fix that can be included here

**Comment by jbloxham** [comment]
Im not actually particularly familiar with the console errors fix, but im pretty sure its distinct from this bug, and probably deserves its own PR

**Comment by vontell** [comment]
I think it is a one liner; mind if I add it to this PR? Also, how would I test this PR? I pulled the relevant code in server but get that `Task 'runFromClient' not found in root project 'battlecode-scaffold-2017'.`

**Comment by vontell** [comment]
For reference, the console error is simply that the websocket tries to connect in `poll` when the server is not even ready, so it would just require a blind try-catch.

`websocket.ts:34 WebSocket connection to 'ws://localhost:6175/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`

**Comment by ygina** [comment]
You could just set it up in another PR, considering they are separate issues.

**Comment by vontell** [comment]
Oh my bad, I thought they were related; this PR and the server both address the polling rate, and the console error has to do with the polling rate. I'll create a new issue for that.

**Comment by kazimuth** [comment]
@vontell Also, that doesn't fix the error:
https://groups.google.com/a/chromium.org/forum/#!topic/chromium-discuss/b3JTbVns89c

**Comment by vontell** [comment]
Welp my bad again, strange issue.

**Comment by kazimuth** [comment]
It's super annoying, chrome doesn't let you disable that for whatever reason :(

We could call console.clear every second...

**Comment by jbloxham** [comment]
at the very least, we don't need to be polling before scaffold.ts has called `gradle runFromClient`. that would cut down on most of the spam

**Comment by kazimuth** [comment]
They might run it in the terminal and expect it to show up in the client, though? That's how it currently works.

Maybe we should just put a big header in the console that says IGNORE THESE ERRORS, you know?

**Comment by jbloxham** [comment]
Is that feature even documented? I doubt how many teams would care about us taking away that functionality when starting matches from the client is almost strictly better. At any rate, silencing those messages seems like a bigger QoL improvement than maintaining that functionality, IMO.

**Comment by vontell** [comment]
Since the error message is always the same, we might be able to replace `window.console.log` with `window.console.log.replace("The error string...", "");`, which gets called by a listener on the `window.console.log` object (while only running the replace command when "The error string..." is present to avoid infinite listening loops)

**Comment by jbloxham** [comment]
Tested in Windows and Unix. You may merge when ready.

**Pull request merged**
