### PR TITLE
Load match file at startup

### PR DESCRIPTION
**Pull request by kazimuth**
For the website.

### CODE REVIEW

**Comment by axc** [comment]
Minor, but some of the fonts aren't loading:
screen shot 2017-01-11 at 9 20 42 pm

**Comment by kazimuth** [comment]
@axc I can fix that

**Comment by kazimuth** [comment]
@axc for now just add the following to the page:
```
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Graduate">
```

**Comment by axc** [comment]
Works!

**Pull request merged**
