### PR TITLE
UPS Slider

### PR DESCRIPTION
**Pull request by ygina**
View your matches at any rate between 1 to 156 UPS. #151

### CODE REVIEW

**Comment by vontell** [comment]
Shouldn't there still be the ability to go backwards in time? Also, I think a "reset" button to bring the slider back to the default UPS would be helpful

**Comment by ygina** [comment]
Hm we could add rewinding back. I just thought the feature cluttered the controls bar and wasn't particularly useful for competitors.

**Comment by vontell** [comment]
I talked to some competitors and they say the rewind would be useful if it was slower; how about changing the lower bound of the slider from 0 to, say, -20? Also, for the result to default, a tiny reset button could work.

**Comment by ygina** [comment]
I don't think the reset button is necessary. I'd rather leave the controls uncluttered.

**Comment by ygina** [comment]
As for rewinding, I'd rather add a button that toggles between forwards and backwards, and leave the slider for the magnitude of the UPS. But do you think this change is really necessary? I also had problems with how the timeline glitched, and the messy logic needed to make sure all the buttons were set correctly.

**Comment by ygina** [comment]
I'm still generally against this rewinding implementation. Now the user has to be careful not to go beyond 0 if they just want to slow down the playback. The way the timeline and round number glitches is also quite disturbing.

**Comment by vontell** [comment]
Yeah im not sure how to fix the rewind glitching on the timeline and round number, but that was an issue with the old implementation anyways. Anyhow, from my testing, I think this is ready to be merged if you guys think the behavior is appropriate.

**Pull request merged**
